/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        canvas: "#0a0a0a",
        "canvas-soft": "#141414",
        "canvas-paper": "#ededed",
        surface: "#1a1a1a",
        "surface-hover": "#1e1e1e",
        brand: "#FF5722",
        "brand-dim": "rgba(255,87,34,0.10)",
        "brand-light": "rgba(255,87,34,0.15)",
        "on-primary": "#ffffff",
        "text-primary": "#f5f5f5",
        "text-secondary": "#a3a3a3",
        ash: "#808080",
        mute: "#525252",
        graphite: "#2a2a2a",
        border: "#262626",
        success: "#10B981",
        error: "#DC2626",
        "link-blue": "#3B82F6",
      },
      spacing: {
        xxs: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        section: "64px",
        "section-lg": "96px",
      },
      borderRadius: {
        xs: "4px",
        sm: "6px",
        md: "8px",
        lg: "10px",
        card: "16px",
        pill: "9999px",
      },
      fontSize: {
        "display-hero": ["48px", { lineHeight: "53px", letterSpacing: "-1.68px", fontWeight: "400" }],
        "display-lg": ["36px", { lineHeight: "40px", letterSpacing: "-0.72px", fontWeight: "400" }],
        "display-md": ["32px", { lineHeight: "36px", letterSpacing: "-0.64px", fontWeight: "400" }],
        "heading-lg": ["22px", { lineHeight: "28px", letterSpacing: "-0.22px", fontWeight: "500" }],
        "heading-md": ["20px", { lineHeight: "26px", letterSpacing: "-0.20px", fontWeight: "500" }],
        body: ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        caption: ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "caption-tight": ["13px", { lineHeight: "17px", fontWeight: "500" }],
        meta: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "mono-eyebrow": ["11px", { lineHeight: "16px", letterSpacing: "0.88px", fontWeight: "400" }],
        button: ["16px", { lineHeight: "20px", fontWeight: "600" }],
        "button-sm": ["14px", { lineHeight: "18px", fontWeight: "500" }],
      },
      fontFamily: {
        sans: ["Inter", "SF Pro Display", "system-ui"],
        mono: ["JetBrains Mono", "SF Mono", "monospace"],
      },
    },
  },
  plugins: [],
};
