/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        canvas: "#0b0b0b",
        "canvas-soft": "#212121",
        "canvas-paper": "#ededed",
        brand: "#f36458",
        "on-primary": "#ffffff",
        ash: "#b9b9b9",
        mute: "#797979",
        graphite: "#353535",
        success: "#37cd84",
        error: "#dd0000",
        "link-blue": "#55beff",
      },
      spacing: {
        xxs: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        section: "64px",
        "section-lg": "96px",
      },
      borderRadius: {
        xs: "4px",
        sm: "6px",
        md: "8px",
        lg: "10px",
        card: "16px",
        pill: "9999px",
      },
      fontSize: {
        "display-hero": ["48px", { lineHeight: "53px", letterSpacing: "-1.68px", fontWeight: "400" }],
        "display-lg": ["36px", { lineHeight: "40px", letterSpacing: "-0.72px", fontWeight: "400" }],
        "display-md": ["32px", { lineHeight: "36px", letterSpacing: "-0.64px", fontWeight: "400" }],
        "heading-lg": ["22px", { lineHeight: "28px", letterSpacing: "-0.22px", fontWeight: "500" }],
        "heading-md": ["20px", { lineHeight: "26px", letterSpacing: "-0.20px", fontWeight: "500" }],
        body: ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        caption: ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "caption-tight": ["13px", { lineHeight: "17px", fontWeight: "500" }],
        meta: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "mono-eyebrow": ["11px", { lineHeight: "16px", letterSpacing: "0.88px", fontWeight: "400" }],
        button: ["16px", { lineHeight: "20px", fontWeight: "600" }],
        "button-sm": ["14px", { lineHeight: "18px", fontWeight: "500" }],
      },
      fontFamily: {
        sans: ["Inter", "SF Pro Display", "system-ui"],
        mono: ["Geist Mono", "SF Mono", "monospace"],
      },
    },
  },
  plugins: [],
};
