export const strings = {
  app: {
    name: 'Nexvy',
    tagline: 'Your fitness, unified.',
  },
  auth: {
    welcomeBack: 'Welcome back',
    signInTo: 'Sign in to Nexvy.',
    createAccount: 'Create your account',
    getStarted: 'Get Started',
    email: 'Email Address',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    forgotPassword: 'Forgot Password?',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    resetPassword: 'Reset Password',
    sendResetLink: 'Send Reset Link',
    backToSignIn: 'Back to Sign In',
    orContinueWith: 'Or continue with',
    googleSignIn: 'Continue with Google',
    appleSignIn: 'Continue with Apple',
  },
  onboarding: {
    slide1Title: 'Track Your Strength',
    slide1Subtitle: 'Log workouts, track sets, and beat your personal records with Hevy-style precision.',
    slide2Title: 'AI Nutrition Tracking',
    slide2Subtitle: 'Snap a photo or scan a barcode. Our AI logs your macros instantly.',
    slide3Title: 'Movement & Activity',
    slide3Subtitle: 'Map your runs, monitor your steps, and own every mile.',
    getStarted: 'Get Started',
    next: 'Next',
    skip: 'Skip',
  },
  setup: {
    personalDetails: 'Personal Details',
    tellUsAboutYou: 'Tell us about yourself',
    age: 'Age',
    weight: 'Weight',
    height: 'Height',
    biologicalSex: 'Biological Sex',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    fitnessGoal: 'Your Fitness Goal',
    whatBringsYou: 'What brings you to Nexvy?',
    buildMuscle: 'Build Muscle',
    loseFat: 'Lose Fat',
    recomposition: 'Recomposition',
    endurance: 'Endurance',
    maintain: 'Maintain',
    activityLevel: 'Activity Level',
    howActive: 'How active are you?',
    sedentary: 'Sedentary',
    light: 'Lightly Active',
    moderate: 'Moderately Active',
    veryActive: 'Very Active',
    notifications: 'Enable Notifications',
    notificationsSubtitle: 'Get reminders for workouts and meals',
    completeSetup: 'Complete Setup',
    kg: 'kg',
    cm: 'cm',
  },
  tabs: {
    home: 'Home',
    workout: 'Workout',
    nutrition: 'Nutrition',
    activity: 'Activity',
    profile: 'Profile',
  },
  workout: {
    startWorkout: 'Start Workout',
    endWorkout: 'End Workout',
    pauseWorkout: 'Pause',
    resumeWorkout: 'Resume',
    addExercise: 'Add Exercise',
    exercisePicker: 'Exercise Picker',
    searchExercises: 'Search exercises...',
    sets: 'Sets',
    reps: 'Reps',
    weight: 'Weight',
    warmup: 'Warmup',
    personalRecord: 'PR',
    restTimer: 'Rest Timer',
    skipRest: 'Skip',
    history: 'History',
    noWorkoutsYet: 'No workouts yet',
    startYourFirst: 'Start your first workout',
    totalVolume: 'Total Volume',
    duration: 'Duration',
    completed: 'Completed',
    quickStart: 'Quick Start',
  },
  nutrition: {
    calories: 'Calories',
    protein: 'Protein',
    carbs: 'Carbs',
    fat: 'Fat',
    breakfast: 'Breakfast',
    lunch: 'Lunch',
    dinner: 'Dinner',
    snacks: 'Snacks',
    logFood: 'Log Food',
    searchFood: 'Search food...',
    scanBarcode: 'Scan Barcode',
    snapPhoto: 'Snap Photo',
    describeMeal: 'Describe Meal',
    servingGrams: 'Serving (g)',
    addFood: 'Add Food',
    removeFood: 'Remove',
    todaysLog: "Today's Log",
    remaining: 'Remaining',
    noMealsLogged: 'No meals logged today',
    logYourFirstMeal: 'Log your first meal',
    sourceBarcode: 'Barcode',
    sourcePhotoAI: 'AI Photo',
    sourceTextAI: 'AI Text',
    sourceManual: 'Manual',
  },
  activity: {
    run: 'Run',
    walk: 'Walk',
    cycle: 'Cycle',
    hike: 'Hike',
    other: 'Other',
    startRun: 'Start Run',
    stopRun: 'Stop Run',
    pauseRun: 'Pause',
    resumeRun: 'Resume',
    distance: 'Distance',
    pace: 'Pace',
    time: 'Time',
    caloriesBurned: 'Calories Burned',
    steps: 'Steps',
    elevation: 'Elevation',
    noActivitiesYet: 'No activities yet',
    logYourFirstActivity: 'Log your first activity',
    recentRuns: 'Recent Runs',
    thisWeek: 'This Week',
  },
  profile: {
    editProfile: 'Edit Profile',
    settings: 'Settings',
    progress: 'Progress',
    achievements: 'Achievements',
    weightHistory: 'Weight History',
    workoutStreak: 'Workout Streak',
    totalWorkouts: 'Total Workouts',
    totalDistance: 'Total Distance',
    personalBests: 'Personal Bests',
    darkMode: 'Dark Mode',
    notifications: 'Notifications',
    healthKit: 'HealthKit Sync',
    weightUnit: 'Weight Unit',
    about: 'About',
    signOut: 'Sign Out',
    version: 'Version',
  },
  common: {
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    loading: 'Loading...',
    error: 'Something went wrong',
    tryAgain: 'Try Again',
    offline: 'Offline — changes will sync',
    syncing: 'Syncing...',
    done: 'Done',
    confirm: 'Confirm',
    search: 'Search',
    noResults: 'No results',
    clear: 'Clear',
  },
  errors: {
    networkError: 'Network error. Please check your connection.',
    authFailed: 'Authentication failed. Please try again.',
    invalidEmail: 'Please enter a valid email address.',
    weakPassword: 'Password must be at least 6 characters.',
    passwordsDontMatch: 'Passwords do not match.',
    required: 'This field is required.',
    invalidWeight: 'Please enter a valid weight.',
    invalidHeight: 'Please enter a valid height.',
    invalidAge: 'Please enter a valid age.',
    photoAnalysisFailed: 'Could not analyse photo. Please try again.',
    barcodeNotFound: 'Product not found. Try entering manually.',
    gpsPermissionDenied: 'Location permission is required for GPS tracking.',
    cameraPermissionDenied: 'Camera permission is required.',
  },
} as const;
